name: Release application

on:
  workflow_dispatch:

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Create token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: cfy-k8s-lab
      - name: Deploy version to DEV
        uses: Cloud-for-You/gh_action_deploy-apps@main
        with:
          repository: cfy-k8s-lab/ops
          ref: env/dev
          path: ops-repo-dev
          token: ${{ steps.app-token.outputs.token }}
          deployment_file: foo.yaml
          jsonpath: "$.spec.tag"
          value: ${{ github.run_id }}
          push: true
          pull_request: false

  tag-release-version:
    runs-on: ubuntu-latest
    needs:
      - deploy-to-dev
    steps:
      - name: Create semvers TAG
        id: release-tag
        run: |
          VERSION="$(printf "%d.%d.%d" $((RANDOM%5+1)) $((RANDOM%10)) $((RANDOM%10)))"
          PATCHED="$(echo "$VERSION" | awk -F. '{printf "%d.%d.%d",$1,$2,$3+1}')"
          FINAL_VERSION="${PATCHED}-build-${GITHUB_RUN_NUMBER:-local}"
          echo "version=$FINAL_VERSION" >> "$GITHUB_OUTPUT"
      - name: Create token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: cfy-k8s-lab
      - name: Create/Update PR to TEST
        uses: Cloud-for-You/gh_action_deploy-apps@main
        with:
          repository: cfy-k8s-lab/ops
          ref: env/test
          path: ops-repo-test
          token: ${{ steps.app-token.outputs.token }}
          deployment_file: foo.yaml
          jsonpath: "$.spec.tag"
          value: ${{ steps.release-tag.outputs.version }}
          push: false
          pull_request: true
