name: Release application

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: cfy-k8s-lab

      - name: Checkout OPS repository
        uses: actions/checkout@v7
        with:
          repository: cfy-k8s-lab/ops
          ref: env/dev
          token: ${{ steps.app-token.outputs.token }}
          path: ops-repo

      - name: DEBUG
        run: |
          ls -la ops-repo
  
    #- name: Deploy version
    #  uses: Cloud-for-You/gh_action_deploy-apps@main
    #  with:
    #    repository: "cfy-k8s-lab/ops"
    #    branch: "main"
    #    token: ${{ steps.app-token.outputs.token }}
    #    deployment_file: "config/app.json"
    #    jsonpath: "$.spec.tag"
    #    value: "5"
    #    push: true
    #    pull_request: false
